window.dataLayer=window.dataLayer||[];
var Piano={produto:{validaConfiguracoes:function(){if(Piano.util.trocarConfiguracoes()){switch(Piano.variaveis.getNomeProduto()){case "acervo":Piano.variaveis.codigoProduto="OG04";break;case "jornaldigital":Piano.variaveis.codigoProduto="OG01";break;case "quem-acontece":case "marie-claire":case "casa-e-jardim":case "crescer":case "auto-esporte":case "epoca":case "epoca-negocios":case "galileu":case "globo-rural":case "pegn":case "vogue":case "casa-vogue":case "glamour":case "gq":case "monet":Piano.variaveis.codigoProduto="revistas";
break;default:Piano.variaveis.fazerRequisicaoBarramento=!1}Piano.construtor.initTp();return!0}return!1}},variaveis:{ambientesAceitos:"int,qlt,prd",statusHttpObterAutorizacaoAcesso:"400,404,406,500,502,503,504",statusHttpObterAssinaturaInadimplente:"400,404,500,502,503,504",codigoProduto:"OG03",fazerRequisicaoBarramento:!0,constante:{cookie:{GCOM:"GLBID",UTP:"_utp",RTIEX:"_rtiex",AMBIENTE:"ambientePiano"},metricas:{EVENTO_SEM_ACAO:"sem acao",ERRO:"Erro"},krux:{SEGMENTACOES:"kxglobo_segs",KRUXLIGADO:"krux-ligado"},
util:{IP:"127.0.0.1",AMBIENTE:"ambiente-desejado",DEBUG:"debug-piano"}},isConteudoExclusivo:function(){return window.conteudoExclusivo?!0:!1},getAmbientePiano:function(){if(-1<Piano.variaveis.ambientesAceitos.indexOf(Piano.util.getValorParametroNaUrl(Piano.variaveis.constante.util.AMBIENTE)))return Piano.cookies.set(Piano.variaveis.constante.cookie.AMBIENTE,Piano.util.getValorParametroNaUrl(Piano.variaveis.constante.util.AMBIENTE),1),Piano.util.getValorParametroNaUrl(Piano.variaveis.constante.util.AMBIENTE);
"false"==Piano.util.getValorParametroNaUrl(Piano.variaveis.constante.util.AMBIENTE)&&Piano.cookies.set(Piano.variaveis.constante.cookie.AMBIENTE,"",-1);return Piano.cookies.get(Piano.variaveis.constante.cookie.AMBIENTE)?Piano.cookies.get(Piano.variaveis.constante.cookie.AMBIENTE):-1<Piano.variaveis.ambientesAceitos.indexOf(window.ambienteUtilizadoPiano)?window.ambienteUtilizadoPiano:"prd"},getTipoConteudoPiano:function(){return window.tipoConteudoPiano},executouPageview:function(){return window.executouPageview?
!0:!1},getNomeProduto:function(){return window.nomeProdutoPiano},getServicoId:function(){return"oglobo"===Piano.variaveis.getNomeProduto()||"blogs"===Piano.variaveis.getNomeProduto()||"kogut"===Piano.variaveis.getNomeProduto()?"4975":Piano.util.isRevista()?"6710":"acervo"===Piano.variaveis.getNomeProduto()||"jornaldigital"===Piano.variaveis.getNomeProduto()?"3981":"0000"}},janelaAnonima:{retry:function(a,b){var c=0,d=!1,e=window.setInterval(function(){a()&&(window.clearInterval(e),b(d));50<c++&&(window.clearInterval(e),
d=!0,b(d))},10)},isIE10OrLater:function(a){a=a.toLowerCase();return 0===a.indexOf("msie")&&0===a.indexOf("trident")?!1:(a=/(?:msie|rv:)\s?([\d\.]+)/.exec(a))&&10<=parseInt(a[1],10)?!0:!1},detectPrivateMode:function(a){if(window.webkitRequestFileSystem)window.webkitRequestFileSystem(window.TEMPORARY,1,function(){c=!1},function(a){c=!0});else if(window.indexedDB&&/Firefox/.test(window.navigator.userAgent)){try{var b=window.indexedDB.open("test")}catch(d){var c=!0}"undefined"===typeof c&&Piano.janelaAnonima.retry(function(){return"done"===
b.readyState?!0:!1},function(a){a||(c=b.result?!1:!0)})}else if(Piano.janelaAnonima.isIE10OrLater(window.navigator.userAgent)){c=!1;try{window.indexedDB||(c=!0)}catch(d){c=!0}}else if(window.localStorage&&/Safari/.test(window.navigator.userAgent)){try{window.localStorage.setItem("test",1)}catch(d){c=!0}"undefined"===typeof c&&(c=!1,window.localStorage.removeItem("test"))}Piano.janelaAnonima.retry(function(){return"undefined"!==typeof c?!0:!1},function(b){a(c)})}},cookies:{set:function(a,b,c){var d=
new Date;d.setDate(d.getDate()+c);document.cookie=a+"="+escape(b)+(null==c?"":";expires="+d.toUTCString())+"; path=/;domain=."+location.hostname.split(".").reverse()[1]+"."+location.hostname.split(".").reverse()[0]},get:function(a){return(match=document.cookie.match(new RegExp(a+"=([^;]+)")))?unescape(match[1].toString()):""}},krux:{tem:function(){return window.localStorage.getItem(Piano.variaveis.constante.krux.SEGMENTACOES)?!0:!1},ligado:function(){var a=Piano.variaveis.constante.krux.KRUXLIGADO,
b=Piano.util.getValorParametroNaUrl(a);return"false"==b&&"prd"!=window.ambienteUtilizadoPiano?(Piano.cookies.set(a,b,1),!1):"true"==b||"prd"==window.ambienteUtilizadoPiano?(Piano.cookies.set(a,"",-1),!0):"false"==Piano.cookies.get(Piano.variaveis.constante.krux.KRUXLIGADO)?!1:!0},obtemSegmentacao:function(){if(Piano.krux.tem()&&Piano.krux.ligado())for(var a=window.localStorage.getItem(Piano.variaveis.constante.krux.SEGMENTACOES).split(","),b=0;b<a.length;b++)tp.push(["setCustomVariable",a[b],a[b]])}},
metricas:{enviaEventosGA:function(a,b){dataLayer.push({event:"EventoGAPiano",eventoGACategoria:"Piano",eventoGAAcao:a,eventoGARotulo:b})},montaRotuloGA:function(){return window.regrasTiny&&window.regrasTiny.nomeExperiencia?window.subsegmentacaoPiano?regrasTiny.nomeExperiencia+" - "+subsegmentacaoPiano:regrasTiny.nomeExperiencia:window.nomeExperiencia?window.subsegmentacaoPiano?window.nomeExperiencia+" - "+subsegmentacaoPiano:window.nomeExperiencia:" "},setLimiteContagem:function(a){_GAContagem=_GALimite=
"-";a&&(_GAContagem=""+a.views,1==_GAContagem.length&&(_GAContagem="0"+_GAContagem),_GALimite=a.nomeExperiencia+" : "+a.maxViews)},identificarPassagemRegister:function(a){var b=Piano.variaveis.constante.metricas.EVENTO_SEM_ACAO;Piano.cookies.get(Piano.variaveis.constante.cookie.RTIEX)&&(b=-1!=a.fluxo.indexOf("hardwall")?"register-hardwall-passou":"register-contagem-passou",Piano.cookies.set(Piano.variaveis.constante.cookie.RTIEX,"",-1));return b},executaAposPageview:function(a){Piano.variaveis.executouPageview()||
(regrasTiny.fluxo=window.tpContext?tpContext.toLowerCase():"-",regrasTiny.nomeExperiencia=window.nomeExperiencia?window.nomeExperiencia:"",Piano.metricas.setLimiteContagem(regrasTiny),"undefined"==typeof a&&Piano.metricas.enviaEventosGA(Piano.metricas.identificarPassagemRegister(regrasTiny),Piano.metricas.montaRotuloGA()),executouPageview=!0)}},banner:{mostrarFooter:function(a){Piano.util.adicionarCss("<link rel='stylesheet' type='text/css' href='https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/footer-piano/"+
a+"/styles/styles.css'>");Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/footer-piano/"+a+"/scripts/novo-banner-footer.js")},mostrarBotaoAssinaturaHeaderFooter:function(a){Piano.util.adicionarCss("<link rel='stylesheet' type='text/css' href='https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/banner-header-footer-piano/"+a+"/styles/styles.css'>");Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+Piano.util.montaUrlStg()+
".infoglobo.com.br/paywall/banner-header-footer-piano/"+a+"/scripts/banner-header-footer-piano.js")}},register:{mostrarBarreira:function(a){Piano.util.adicionarCss("<link rel='stylesheet' type='text/css' href='https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/register-piano/"+a+"/styles/styles.css'>");Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/register-piano/"+a+"/scripts/nova-tela-register.js");Piano.cookies.set(Piano.variaveis.constante.cookie.UTP,
"",-1);Piano.metricas.enviaEventosGA("Exibicao Register",Piano.metricas.montaRotuloGA());Piano.cookies.set(Piano.variaveis.constante.cookie.RTIEX,!0,1)}},paywall:{redirecionarBarreira:function(a){Piano.metricas.enviaEventosGA("Barreira",Piano.metricas.montaRotuloGA());Piano.cookies.set(Piano.variaveis.constante.cookie.UTP,"",-1);setTimeout(function(){window.location=a},200)}},comunicado:{mostrarInformacao:function(a){Piano.util.adicionarCss("<link rel='stylesheet' type='text/css' href='https://static"+
Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/comunicacao-piano/"+a+"/styles/styles.css'>");Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/comunicacao-piano/"+a+"/scripts/comunicacao-piano.js")}},adblock:{mostrarAdBlock:function(a){Piano.util.adicionarCss("<link rel='stylesheet' type='text/css' href='https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/adblock-piano/styles/styles.css'>");Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+
Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/adblock-piano/"+a+"/scripts/adblock-piano.js")}},bloqueios:{liberarEsc:function(){Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/bloqueio/liberaTeclado.js")},bloqueiaViewMode:function(){Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/bloqueio/bloqueiaViewmode.js")}},parceiro:{mostraFooterParceiro:function(a){Piano.util.adicionarCss("<link rel='stylesheet' type='text/css' href='https://static"+
Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/footer-parceiros-piano/"+a+"/styles/styles.css'>");Piano.xmlHttpRequest.geraScriptNaPagina("https://static"+Piano.util.montaUrlStg()+".infoglobo.com.br/paywall/footer-parceiros-piano/"+a+"/scripts/footer-parceiros-piano.js")}},inadimplente:{getLinkAssinatura:function(a){for(var b=0;b<a.length;b++)if("assinatura"==a[b].rel)return a[b].href;return""}},xmlHttpRequest:{geraScriptNaPagina:function(a){var b=new XMLHttpRequest;b.open("GET",a);b.send();
b.onreadystatechange=function(){if(4==this.readyState&&200==this.status){var a=b.responseText,d=document.createElement("script");d.innerHTML=a;document.body.appendChild(d)}}},fazRequisicaoBarramentoApiObterAssinaturaInadimplente:function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.setRequestHeader("Accept","application/json");b.setRequestHeader("Content-Type","application/json");b.send();4==b.readyState&&(200==b.status?(a=JSON.parse(b.responseText).situacaoPagamento.toLowerCase(),tp.push(["setCustomVariable",
"situacaoPagamento",a])):(0!=b.status&&-1<Piano.variaveis.statusHttpObterAssinaturaInadimplente.indexOf(b.status)&&Piano.metricas.enviaEventosGA(Piano.variaveis.constante.metricas.ERRO,"Ao obter inadimplente da API - "+b.status),Piano.metricas.enviaEventosGA(Piano.variaveis.constante.metricas.ERRO,"Ao obter inadimplente - "+b.status)))},fazRequisicaoBarramentoApiAutorizacaoAcesso:function(a){var b=JSON.stringify({"token-autenticacao":a,ipUsuario:Piano.variaveis.constante.util.IP,codigoProduto:Piano.variaveis.codigoProduto}),
c=new XMLHttpRequest;c.open("POST",Piano.configuracao.jsonConfiguracaoTinyPass[Piano.variaveis.getAmbientePiano()].urlVerificaLeitor,!1);c.setRequestHeader("Accept","application/json");c.setRequestHeader("Content-Type","application/json");c.send(b);if(4==c.readyState)if(200==c.status){b=JSON.parse(c.responseText);tp.push(["setCustomVariable","autorizado",b.autorizado]);var c=!1,d="",e="";"undefined"!=typeof b.motivo&&(d=b.motivo.toLowerCase());"undefined"!=typeof b.temTermoDeUso&&(c=b.temTermoDeUso);
"undefined"!=typeof b.link&&(e=Piano.inadimplente.getLinkAssinatura(b.link));e=Piano.autenticacao.isAutorizado(c,d,b.autorizado,e);tp.push(["setCustomVariable","logado",e]);tp.push(["setCustomVariable","temTermo",c]);tp.push(["setCustomVariable","motivo",d]);a={autorizado:b.autorizado,motivo:d,logado:e,temTermoDeUso:c,glbid:a,produto:Piano.variaveis.getNomeProduto(),codProduto:Piano.variaveis.codigoProduto};a=btoa(encodeURI(JSON.stringify(a)));Piano.cookies.set(Piano.variaveis.constante.cookie.UTP,
a,1)}else Piano.metricas.enviaEventosGA(Piano.variaveis.constante.metricas.ERRO,"Ao obter autorizacao da API - "+c.status+" - "+a),tp.push(["setCustomVariable","autorizado",!0]),tp.push(["setCustomVariable","logado",!0]),tp.push(["setCustomVariable","motivo","erro"])}},autenticacao:{isLogadoCadun:function(a,b){a||(b&&Piano.cookies.set(Piano.variaveis.constante.cookie.UTP,"",-1),Piano.cookies.get(Piano.variaveis.constante.cookie.RTIEX)&&Piano.cookies.set(Piano.variaveis.constante.cookie.RTIEX,"",-1));
return""!=a},verificaUsuarioLogadoNoBarramento:function(a,b){if(Piano.autenticacao.isLogadoCadun(a,b)){if(b){var c=JSON.parse(decodeURI(atob(b)));if(a==c.glbid&&("undefined"==typeof c.produto||c.produto==Piano.variaveis.getNomeProduto())){tp.push(["setCustomVariable","autorizado",c.autorizado]);tp.push(["setCustomVariable","motivo",c.motivo]);tp.push(["setCustomVariable","logado",c.logado]);tp.push(["setCustomVariable","temTermo",c.temTermoDeUso]);return}Piano.cookies.set(Piano.variaveis.constante.cookie.UTP,
"",-1)}Piano.variaveis.fazerRequisicaoBarramento&&Piano.xmlHttpRequest.fazRequisicaoBarramentoApiAutorizacaoAcesso(a)}},isAutorizado:function(a,b,c,d){if(c||"indisponivel"==b||0!=a)return c&&d&&Piano.xmlHttpRequest.fazRequisicaoBarramentoApiObterAssinaturaInadimplente(d),!0;Piano.cookies.get(Piano.variaveis.constante.cookie.RTIEX)&&Piano.cookies.set(Piano.variaveis.constante.cookie.RTIEX,"",-1);return!1}},util:{isSection:function(){return"section"==Piano.variaveis.getTipoConteudoPiano()?!0:!1},isTipoConteudoUndefined:function(){"undefined"==
typeof Piano.variaveis.getTipoConteudoPiano()&&Piano.metricas.enviaEventosGA(Piano.variaveis.constante.metricas.ERRO,"Variavel tipoConteudoPiano nao esta definida nesta url - "+document.location.href)},extraiParametrosCampanhaDaUrl:function(){for(var a,b=Piano.util.getWindowLocationSearch(),c=["utm_medium","utm_source"],d=[],e=0;e<c.length;e++)a=c[e],-1!=b.indexOf(a+"=")&&(a=new RegExp("[?(&)]"+a+"=([^&#]*)"),(a=b.match(a)[1])&&d.push(a));0<d.length&&tp.push(["setCustomVariable","utm",d.join(";")]);
-1!=b.indexOf("utm_campaign=")&&(a=/utm_campaign=(\w+)/,(b=b.match(a)[1])&&tp.push(["setCustomVariable","campanha",b]))},isOrigemBuscador:function(){var a=/(ia_archiver)|(Googlebot)|(Mediapartners-Google)|(AdsBot-Google)|(msnbot)|(Yahoo! Slurp)|(ZyBorg)|(Ask Jeeves\/Teoma)|(bingbot)|(cXensebot)/.test(navigator.userAgent);tp.push(["setCustomVariable","buscador",a]);return a},montaUrlStg:function(){return"prd"!=Piano.variaveis.getAmbientePiano()?"-stg":""},temParametroNaUrl:function(a){return-1!=Piano.util.getWindowLocationSearch().indexOf(a)?
!0:!1},getValorParametroNaUrl:function(a){return Piano.util.temParametroNaUrl(a)?Piano.util.getWindowLocationSearch().match(new RegExp("[?(&)]"+a+"=([^&#]*)"))[1]:"sem parametro"},isDebug:function(){var a=Piano.variaveis.constante.util.DEBUG,b=Piano.util.getValorParametroNaUrl(a);return"true"==b?(Piano.cookies.set(a,b,1),!0):"false"==b?(Piano.cookies.set(a,"",-1),!1):Piano.cookies.get(Piano.variaveis.constante.util.DEBUG)?!0:!1},detectaBurlesco:function(){window.onload=function(){"undefined"==typeof addControlContent&&
dataLayer.push({event:"EventoGAPiano",eventoGACategoria:"ExtensaoBurlesco",eventoGAAcao:"Sim",eventoGARotulo:"",eventoGAInteracao:"true"})}},isDominioOGlobo:function(){var a=/:\/\/(.*?)\//,b=Piano.util.getWindowLocationHref();return-1<b.match(a)[1].indexOf("oglobo")||-1<b.match(a)[1].indexOf("globoi")&&-1==b.match(a)[1].indexOf("edg")?b.match(a)[1]:""},trocarConfiguracoes:function(){var a,b=!1,c=Piano.cookies.get(Piano.variaveis.constante.cookie.UTP);c&&(a=JSON.parse(decodeURI(atob(c))));("undefined"==
typeof a||"undefined"==typeof a.produto||a.produto==Piano.variaveis.getNomeProduto())&&"undefined"!=typeof a||(!Piano.util.isDominioOGlobo()||"acervo"!=Piano.variaveis.getNomeProduto()&&"jornaldigital"!=Piano.variaveis.getNomeProduto())&&!Piano.util.isRevista()&&Piano.util.isDominioOGlobo()||(b=!0);return b},callbackMeter:function(a){regrasTiny=a;Piano.metricas.executaAposPageview()},callbackMeterExpired:function(a){regrasTiny=a;Piano.metricas.executaAposPageview(!0)},getWindowLocationSearch:function(){return window.location.search},
getWindowLocationHref:function(){return window.location.href},adicionarCss:function(a){var b=document.createElement("div");b.innerHTML=a;document.body.insertBefore(b,document.body.lastChild)},isRevista:function(){return-1<"quem-acontece crescer marie-claire casa-e-jardim vogue casa-vogue gq glamour monet auto-esporte pegn epoca epoca-negocios galileu globo-rural".split(" ").indexOf(Piano.variaveis.getNomeProduto())?!0:!1}}};
Piano.configuracao={jsonConfiguracaoTinyPass:{"int":{idSandboxTinypass:"dXu7dvFKRi",setSandBox:"true",urlSandboxPiano:"https://sandbox.tinypass.com/xbuilder/experience/load?aid=dXu7dvFKRi",urlVerificaLeitor:"https://apiqlt-ig.infoglobo.com.br/relacionamento/v3/funcionalidade/"+Piano.variaveis.getServicoId()+"/autorizacao-acesso",urlDominioPaywall:"https://assinatura.globostg.globoi.com/",urlDominioSiteOGlobo:""+Piano.util.isDominioOGlobo()+"/"},qlt:{idSandboxTinypass:"GTCopIDc5z",setSandBox:"false",
urlSandboxPiano:"https://experience.tinypass.com/xbuilder/experience/load?aid=GTCopIDc5z",urlVerificaLeitor:"https://apiqlt-ig.infoglobo.com.br/relacionamento/v3/funcionalidade/"+Piano.variaveis.getServicoId()+"/autorizacao-acesso",urlDominioPaywall:"https://assinatura.globostg.globoi.com/",urlDominioSiteOGlobo:""+Piano.util.isDominioOGlobo()+"/"},prd:{idSandboxTinypass:"GTCopIDc5z",setSandBox:"false",urlSandboxPiano:"https://experience.tinypass.com/xbuilder/experience/load?aid=GTCopIDc5z",urlVerificaLeitor:"https://api.infoglobo.com.br/relacionamento/v3/funcionalidade/"+
Piano.variaveis.getServicoId()+"/autorizacao-acesso",urlDominioPaywall:"https://assinatura.oglobo.globo.com/",urlDominioSiteOGlobo:""+Piano.util.isDominioOGlobo()+"/"}}};
Piano.construtor={initTp:function(){Piano.util.detectaBurlesco();Piano.util.isTipoConteudoUndefined();tp=window.tp||[];tp.push(["setTags",[Piano.variaveis.getTipoConteudoPiano()]]);tp.push(["setAid",Piano.configuracao.jsonConfiguracaoTinyPass[Piano.variaveis.getAmbientePiano()].idSandboxTinypass]);tp.push(["setSandbox",Piano.configuracao.jsonConfiguracaoTinyPass[Piano.variaveis.getAmbientePiano()].setSandBox]);tp.push(["setDebug",Piano.util.isDebug()]);var a=Piano.util.getWindowLocationHref().split("?")[0];
tp.push(["setPageURL",a]);tp.push(["setZone",Piano.variaveis.getNomeProduto()]);tp.push(["setCustomVariable","nomeProduto",Piano.variaveis.getNomeProduto()]);Piano.janelaAnonima.detectPrivateMode(function(a){tp.push(["setCustomVariable","anonimo",a])});Piano.variaveis.isConteudoExclusivo()&&tp.push(["setCustomVariable","conteudoExclusivo",!0]);Piano.autenticacao.verificaUsuarioLogadoNoBarramento(Piano.cookies.get(Piano.variaveis.constante.cookie.GCOM),Piano.cookies.get(Piano.variaveis.constante.cookie.UTP));
Piano.krux.obtemSegmentacao();tp.push(["setCustomVariable","bannerContadorLigado",!0]);Piano.util.isOrigemBuscador()||Piano.util.extraiParametrosCampanhaDaUrl();tp.push(["addHandler","meterActive",Piano.util.callbackMeter]);tp.push(["addHandler","meterExpired",Piano.util.callbackMeterExpired])}};(function(){Piano.produto.validaConfiguracoes()||Piano.construtor.initTp()})();
(function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)})(Piano.configuracao.jsonConfiguracaoTinyPass[Piano.variaveis.getAmbientePiano()].urlSandboxPiano);
